# Generated by Django 4.2.25 on 2026-01-13 17:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('trabajadores', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionTipoEnsayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Asignación de Ensayo a Técnico',
                'verbose_name_plural': 'Asignaciones de Ensayos a Técnicos',
            },
        ),
        migrations.CreateModel(
            name='DetalleEnsayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ensayo_descripcion', models.CharField(max_length=150, verbose_name='Descripción del Ensayo')),
                ('fecha_limite_ejecucion', models.DateField(verbose_name='Fecha Límite de Ejecución (Entrega Programada)')),
                ('fecha_entrega_real', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Real (Técnico)')),
                ('estado_detalle', models.CharField(choices=[('PENDIENTE', 'Pendiente de Asignación'), ('ASIGNADO', 'Asignado a Técnico'), ('EN_EJECUCION', 'En Ejecución'), ('COMPLETADO', 'Completado por Técnico'), ('VALIDADO', 'Validado por Supervisor')], default='PENDIENTE', max_length=20, verbose_name='Estado del Detalle de Ensayo')),
                ('observaciones_detalle', models.TextField(blank=True, null=True, verbose_name='Observaciones de la Tarea/Ensayo')),
                ('detalle_cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.cotizaciondetalle', verbose_name='Detalle de Cotización de Origen')),
                ('firma_tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_firmados', to='trabajadores.trabajadorprofile', verbose_name='Firma del Técnico (Completado)')),
                ('metodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.metodo', verbose_name='Método de Ensayo')),
                ('norma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.norma', verbose_name='Norma de Ensayo')),
            ],
            options={
                'verbose_name': 'Detalle de Ensayo (Línea de Trabajo)',
                'verbose_name_plural': 'Detalles de Ensayos (Líneas de Trabajo)',
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Laboratorio/Área')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Área')),
            ],
            options={
                'verbose_name': 'Laboratorio/Área',
                'verbose_name_plural': 'Laboratorios/Áreas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote_generado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Lote (V-TIPO-AÑO)')),
                ('codigo_muestra', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Código de Muestra (ID_LAB-TIPO-001)')),
                ('descripcion_muestra', models.TextField(blank=True, null=True, verbose_name='Descripción o Ubicación de Toma (Cliente)')),
                ('masa_aprox_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Masa/Volumen Aprox. (kg/L)')),
                ('fecha_toma_muestra', models.DateField(blank=True, null=True, verbose_name='Fecha Toma (Muestreo)')),
                ('ubicacion_gps', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación GPS (Latitud, Longitud)')),
                ('fecha_recepcion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Recepción en Lab')),
                ('estado_fisico_recepcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado Físico (Recepción/Integridad)')),
                ('ubicacion_almacenamiento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación Muestra (En Almacén)')),
                ('fecha_fabricacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Fabricación (si aplica)')),
                ('fecha_ensayo_rotura', models.DateField(blank=True, null=True, verbose_name='Fecha Prevista de Ensayo de Rotura (si aplica)')),
                ('estado', models.CharField(choices=[('RECIBIDA', 'Recibida en Laboratorio'), ('ASIGNADA', 'Técnico Asignado, Pendiente de Órdenes'), ('EN_ANALISIS', 'Órdenes de Ensayo Generadas/En Curso'), ('RESULTADOS_REGISTRADOS', 'Resultados Registrados (Pendiente de Validación)'), ('VALIDADO', 'Validada (Lista para Informe Final)'), ('ENTREGADO', 'Muestra Entregada/Dispuesta')], default='RECIBIDA', max_length=30, verbose_name='Estado de la Muestra')),
                ('notas_recepcion', models.TextField(blank=True, null=True, verbose_name='Notas de Recepción/Observaciones Internas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('id_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras', to='proyectos.laboratorio', verbose_name='Laboratorio Asociado')),
            ],
            options={
                'verbose_name': 'Muestra de Laboratorio',
                'verbose_name_plural': 'Muestras de Laboratorio',
                'ordering': ['codigo_muestra'],
            },
        ),
        migrations.CreateModel(
            name='TipoEnsayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Ensayo (Catálogo)')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Detallada')),
                ('codigo_interno', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código Interno')),
            ],
            options={
                'verbose_name': 'Tipo de Ensayo',
                'verbose_name_plural': 'Tipos de Ensayos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tipo de Muestra (Ej: Suelo, Agua)')),
                ('prefijo_codigo', models.CharField(max_length=2, unique=True, verbose_name='Prefijo de Codificación (Ej: S, C, A)')),
                ('tipo_laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.laboratorio', verbose_name='Área de Laboratorio Asociada')),
            ],
            options={
                'verbose_name': 'Tipo de Muestra (Catálogo)',
                'verbose_name_plural': 'Tipos de Muestra (Catálogo)',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudEnsayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_solicitud', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código de Solicitud/Orden')),
                ('fecha_solicitud', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Generación de la Solicitud')),
                ('fecha_entrega_programada', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega de Registros (Programada)')),
                ('fecha_entrega_real', models.DateField(blank=True, null=True, verbose_name='Fecha Real de Entrega de Registros')),
                ('estado', models.CharField(choices=[('ASIGNADA', 'Técnicos Asignados'), ('EN_ANALISIS', 'En Curso'), ('COMPLETADA', 'Todos los Ensayos Finalizados'), ('CERRADA', 'Cerrada con Informe')], default='ASIGNADA', max_length=30, verbose_name='Estado de la Solicitud')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('firma_jefe_laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_firmadas', to='trabajadores.trabajadorprofile', verbose_name='Jefe de Laboratorio que Firma')),
                ('generada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_generadas', to='trabajadores.trabajadorprofile', verbose_name='Persona que Elabora la Solicitud')),
                ('muestra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_ensayo', to='proyectos.muestra', verbose_name='Muestra Asociada')),
            ],
            options={
                'verbose_name': 'Solicitud de Ensayo (Cabecera)',
                'verbose_name_plural': 'Solicitudes de Ensayo (Cabeceras)',
            },
        ),
        migrations.CreateModel(
            name='ResultadoEnsayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_ensayo', models.DateField(verbose_name='Fecha de Inicio del Ensayo')),
                ('fecha_fin_ensayo', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización del Ensayo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro en el Sistema')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión / Validación')),
                ('es_reensayo', models.BooleanField(default=False, verbose_name='¿Es Reensayo?')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado por Técnico'), ('VALIDADO', 'Validado por Supervisor'), ('APROBADO', 'Aprobado para Informe'), ('OBSERVADO', 'Observado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20, verbose_name='Estado del Resultado')),
                ('observaciones_tecnicas', models.TextField(blank=True, null=True, verbose_name='Observaciones Técnicas del Ensayo')),
                ('observaciones_revision', models.TextField(blank=True, null=True, verbose_name='Observaciones de Revisión / Supervisor')),
                ('datos_crudos', models.JSONField(blank=True, null=True, verbose_name='Datos Crudos / Curvas / Registros de Equipo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('detalle_ensayo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='proyectos.detalleensayo', verbose_name='Detalle de Ensayo (Tarea)')),
                ('metodo_aplicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.metodo', verbose_name='Método de Ensayo')),
                ('norma_aplicada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.norma', verbose_name='Norma Aplicada')),
                ('resultado_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reensayos', to='proyectos.resultadoensayo', verbose_name='Resultado Original (si es reensayo)')),
                ('supervisor_revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_revisados', to='trabajadores.trabajadorprofile', verbose_name='Supervisor Revisor')),
                ('tecnico_ejecutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_ejecutados', to='trabajadores.trabajadorprofile', verbose_name='Técnico Ejecutor')),
                ('tipo_ensayo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.tipoensayo', verbose_name='Tipo de Ensayo Ejecutado')),
            ],
            options={
                'verbose_name': 'Resultado de Ensayo',
                'verbose_name_plural': 'Resultados de Ensayos',
                'ordering': ['-fecha_inicio_ensayo'],
                'unique_together': {('detalle_ensayo', 'tipo_ensayo')},
            },
        ),
        migrations.CreateModel(
            name='ReporteIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_incidencia', models.CharField(choices=[('CAMBIO', 'Cambio en Solicitud/Alcance'), ('ANULACION', 'Anulación de Ensayo/Detalle'), ('INCREMENTO', 'Incremento de Ensayos'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Tipo de Incidencia')),
                ('detalle_incidencia', models.TextField(verbose_name='Detalle de la Incidencia')),
                ('fecha_ocurrencia', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Ocurrencia')),
                ('representante_cliente', models.CharField(max_length=150, verbose_name='Representante del Cliente (Nombre/Firma)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('responsable_laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_registradas', to='trabajadores.trabajadorprofile', verbose_name='Responsable del Laboratorio (Jefe/Supervisor)')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='proyectos.solicitudensayo', verbose_name='Solicitud de Ensayo Asociada')),
            ],
            options={
                'verbose_name': 'Reporte de Incidencia',
                'verbose_name_plural': 'Reportes de Incidencias',
                'ordering': ['-fecha_ocurrencia'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=255, verbose_name='Nombre del Proyecto')),
                ('codigo_proyecto', models.CharField(max_length=50, unique=True, verbose_name='Código del Proyecto (Interno)')),
                ('descripcion_proyecto', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('monto_cotizacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto de la Cotización Aprobada')),
                ('codigo_voucher', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Voucher/Operación de Pago')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio Real')),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Estimada')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Inicio'), ('EN_CURSO', 'En Curso'), ('MUESTRAS_ASIGNADAS', 'Técnicos Asignados'), ('MUESTRAS_VALIDADAS', 'Muestras Validadas (Listo para Informe)'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado del Proyecto')),
                ('numero_muestras', models.PositiveIntegerField(default=0, verbose_name='Número Total de Muestras (Según Cotización)')),
                ('numero_muestras_registradas', models.PositiveIntegerField(default=0, verbose_name='Número de Muestras con Resultados Finales')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='clientes.cliente', verbose_name='Cliente')),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.cotizacion', verbose_name='Cotización de Origen')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='muestra',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras', to='proyectos.proyecto', verbose_name='Proyecto Asociado'),
        ),
        migrations.AddField(
            model_name='muestra',
            name='recepcionado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras_recepcionadas', to='trabajadores.trabajadorprofile', verbose_name='Recepcionado Por'),
        ),
        migrations.AddField(
            model_name='muestra',
            name='tecnico_responsable_muestra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras_asignadas_principal', to='trabajadores.trabajadorprofile', verbose_name='Técnico Responsable Principal'),
        ),
        migrations.AddField(
            model_name='muestra',
            name='tipo_muestra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='muestras', to='proyectos.tipomuestra', verbose_name='Tipo de Muestra'),
        ),
        migrations.AddField(
            model_name='muestra',
            name='tomada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras_tomadas', to='trabajadores.trabajadorprofile', verbose_name='Tomada Por'),
        ),
        migrations.CreateModel(
            name='EnsayoParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Parámetro')),
                ('unidad', models.CharField(blank=True, max_length=30, null=True, verbose_name='Unidad (MPa, %, g/cm3, etc.)')),
                ('es_numerico', models.BooleanField(default=True, verbose_name='¿Valor Numérico?')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden de Visualización')),
                ('tipo_ensayo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='proyectos.tipoensayo', verbose_name='Tipo de Ensayo')),
            ],
            options={
                'verbose_name': 'Parámetro de Ensayo',
                'verbose_name_plural': 'Parámetros de Ensayo',
                'ordering': ('orden',),
                'unique_together': {('tipo_ensayo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='DocumentoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Informe Técnico Final', max_length=255)),
                ('archivo_pdf', models.FileField(upload_to='informes_finales/%Y/%m/')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('publicado', models.BooleanField(default=False, help_text='Si está marcado, el cliente puede verlo.')),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documento_final', to='proyectos.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='detalleensayo',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_ensayo', to='proyectos.solicitudensayo', verbose_name='Solicitud de Ensayo de Origen'),
        ),
        migrations.AddField(
            model_name='detalleensayo',
            name='tipos_ensayo',
            field=models.ManyToManyField(related_name='detalles_con_asignacion', through='proyectos.AsignacionTipoEnsayo', to='proyectos.tipoensayo', verbose_name='Tipos de Ensayos Asignados'),
        ),
        migrations.AddField(
            model_name='asignaciontipoensayo',
            name='detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='proyectos.detalleensayo', verbose_name='Tarea de Detalle'),
        ),
        migrations.AddField(
            model_name='asignaciontipoensayo',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_ensayos_asignados', to='trabajadores.trabajadorprofile', verbose_name='Técnico (Supervisor) Asignado'),
        ),
        migrations.AddField(
            model_name='asignaciontipoensayo',
            name='tipo_ensayo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_tecnicos', to='proyectos.tipoensayo', verbose_name='Tipo de Ensayo a Ejecutar'),
        ),
        migrations.CreateModel(
            name='ResultadoEnsayoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='Valor Numérico')),
                ('valor_texto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor Textual / Cualitativo')),
                ('cumple', models.BooleanField(blank=True, null=True, verbose_name='¿Cumple Especificación?')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.ensayoparametro', verbose_name='Parámetro Medido')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='proyectos.resultadoensayo', verbose_name='Resultado de Ensayo')),
            ],
            options={
                'verbose_name': 'Valor del Resultado',
                'verbose_name_plural': 'Valores de Resultados',
                'unique_together': {('resultado', 'parametro')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='asignaciontipoensayo',
            unique_together={('detalle', 'tipo_ensayo')},
        ),
    ]
