# Generated by Django 4.2.29 on 2026-03-24 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0001_initial'),
        ('trabajadores', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedencia', models.CharField(max_length=255)),
                ('responsable_cliente', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_recepcion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fabricacion', models.DateField(blank=True, null=True)),
                ('fecha_muestreo', models.DateField(blank=True, null=True)),
                ('fecha_ensayo_programado', models.DateField(blank=True, null=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='servicios.cotizacion')),
                ('responsable_recepcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudEnsayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_solicitud', models.CharField(max_length=50, unique=True, verbose_name='No. DE SOLICITUD')),
                ('estado', models.CharField(choices=[('pendiente', 'PENDIENTE'), ('proceso', 'EN PROCESO'), ('finalizado', 'FINALIZADO')], default='pendiente', max_length=20, verbose_name='ESTADO OPERATIVO')),
                ('fecha_solicitud', models.DateField(default=django.utils.timezone.now, verbose_name='FECHA DE SOLICITUD')),
                ('fecha_entrega_programada', models.DateField(verbose_name='FECHA DE ENTREGA DE REGISTROS (PROGRAMADA)')),
                ('fecha_entrega_real', models.DateField(blank=True, null=True, verbose_name='FECHA REAL DE ENTREGA DE REGISTROS')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_ensayo', to='servicios.cotizacion', verbose_name='No. COTIZACIÓN')),
                ('elaborado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_elaboradas', to='trabajadores.trabajadorprofile', verbose_name='PERSONA QUE ELABORA LA SOLICITUD')),
                ('recepcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_ensayo', to='proyectos.recepcionmuestra', verbose_name='Recepción Asociada')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to='trabajadores.trabajadorprofile', verbose_name='FIRMA JEFE DE LABORATORIO')),
            ],
            options={
                'verbose_name': 'Solicitud de Ensayo',
                'verbose_name_plural': 'Solicitudes de Ensayo',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=255, verbose_name='Nombre del Proyecto')),
                ('codigo_proyecto', models.CharField(max_length=50, unique=True, verbose_name='Código del Proyecto (Interno)')),
                ('descripcion_proyecto', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('monto_cotizacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto de la Cotización Aprobada')),
                ('codigo_voucher', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Voucher/Operación de Pago')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio Real')),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Estimada')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Inicio'), ('EN_CURSO', 'En Curso'), ('MUESTRAS_ASIGNADAS', 'Técnicos Asignados'), ('MUESTRAS_VALIDADAS', 'Muestras Validadas (Listo para Informe)'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado del Proyecto')),
                ('numero_muestras', models.PositiveIntegerField(default=0, verbose_name='Número Total de Muestras (Según Cotización)')),
                ('numero_muestras_registradas', models.PositiveIntegerField(default=0, verbose_name='Número de Muestras con Resultados Finales')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='clientes.cliente', verbose_name='Cliente')),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.cotizacion', verbose_name='Cotización de Origen')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MuestraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_item', models.IntegerField(default=1)),
                ('descripcion', models.CharField(max_length=255)),
                ('masa_aprox', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField(default=1)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('codigo_laboratorio', models.CharField(blank=True, max_length=50, unique=True)),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras', to='proyectos.recepcionmuestra')),
                ('tipo_muestra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.tipomuestra')),
                ('unidad_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='InformeFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_informe', models.CharField(editable=False, max_length=50, unique=True)),
                ('archivo_pdf', models.FileField(upload_to='informes_finales/pdfs/%Y/%m/')),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado_envio', models.CharField(choices=[('pendiente', 'Pendiente de Envío'), ('enviado', 'Enviado al Cliente')], default='pendiente', max_length=20)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('slug_validacion', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='informes_finales/qrs/')),
                ('descargas_count', models.PositiveIntegerField(default=0)),
                ('responsable_firma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes_firmados', to='trabajadores.trabajadorprofile')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informe_final', to='proyectos.solicitudensayo')),
            ],
            options={
                'verbose_name': 'Informe Final',
                'verbose_name_plural': 'Informes Finales',
            },
        ),
        migrations.CreateModel(
            name='IncidenciaSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_incidencia', models.TextField(verbose_name='Detalle de la incidencia')),
                ('fecha_ocurrencia', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de ocurrencia')),
                ('representante_cliente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Representante del Cliente')),
                ('esta_autorizada', models.BooleanField(default=False, help_text='Indica si la incidencia ha sido validada/firmada electrónicamente.', verbose_name='Autorizado')),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Firma')),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_autorizadas', to='trabajadores.trabajadorprofile', verbose_name='Firma de Autorización')),
                ('representante_laboratorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_responsable', to='trabajadores.trabajadorprofile', verbose_name='Responsable del laboratorio (JL / SL)')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='proyectos.solicitudensayo')),
            ],
            options={
                'verbose_name': 'Incidencia de Solicitud',
                'verbose_name_plural': 'Incidencias de Solicitudes',
                'ordering': ['fecha_ocurrencia'],
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicitudEnsayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_ensayo', models.CharField(max_length=255, verbose_name='Descripción')),
                ('norma', models.CharField(max_length=255, verbose_name='Norma de ensayo')),
                ('metodo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Método')),
                ('fecha_entrega_programada', models.DateField(verbose_name='Entrega Programada')),
                ('fecha_entrega_real', models.DateField(blank=True, null=True, verbose_name='Entrega Real')),
                ('aceptado_tecnico', models.BooleanField(default=False, help_text='Check para reemplazar la firma manual del técnico', verbose_name='Aceptación (Firma)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.muestradetalle', verbose_name='Código de Muestra (Lab)')),
                ('servicio_cotizado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.cotizaciondetalle', verbose_name='Servicio/Ensayo')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='proyectos.solicitudensayo')),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trabajadores.trabajadorprofile', verbose_name='Técnico Asignado')),
            ],
            options={
                'verbose_name': 'Detalle de Solicitud',
                'verbose_name_plural': 'Detalles de Solicitudes',
            },
        ),
    ]
