# Generated by Django 4.2.27 on 2026-01-31 20:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajadores', '0001_initial'),
        ('clientes', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=255, verbose_name='Nombre del Proyecto')),
                ('codigo_proyecto', models.CharField(max_length=50, unique=True, verbose_name='Código del Proyecto (Interno)')),
                ('descripcion_proyecto', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('monto_cotizacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto de la Cotización Aprobada')),
                ('codigo_voucher', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Voucher/Operación de Pago')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio Real')),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Estimada')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Inicio'), ('EN_CURSO', 'En Curso'), ('MUESTRAS_ASIGNADAS', 'Técnicos Asignados'), ('MUESTRAS_VALIDADAS', 'Muestras Validadas (Listo para Informe)'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado del Proyecto')),
                ('numero_muestras', models.PositiveIntegerField(default=0, verbose_name='Número Total de Muestras (Según Cotización)')),
                ('numero_muestras_registradas', models.PositiveIntegerField(default=0, verbose_name='Número de Muestras con Resultados Finales')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='clientes.cliente', verbose_name='Cliente')),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.cotizacion', verbose_name='Cotización de Origen')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionMuestraLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.CharField(max_length=50, unique=True)),
                ('responsable_entrega', models.CharField(max_length=255)),
                ('telefono_entrega', models.CharField(blank=True, max_length=50)),
                ('fecha_recepcion', models.DateField()),
                ('hora_recepcion', models.TimeField()),
                ('fecha_muestreo', models.DateField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
                ('recepcionado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trabajadores.trabajadorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MuestraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('masa_aproximada', models.CharField(blank=True, max_length=50)),
                ('codigo_cliente', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('es_adicional', models.BooleanField(default=False)),
                ('codigo_vicaf', models.CharField(max_length=50, unique=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.categoriaservicio')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proyectos.recepcionmuestralote')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.servicio')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.subcategoria')),
            ],
        ),
    ]
