# Generated by Django 4.2.25 on 2026-01-29 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_cotizacion_servicio_general'),
        ('trabajadores', '0002_roltrabajador_remove_trabajadorprofile_role_and_more'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuestraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('masa_aproximada', models.CharField(blank=True, max_length=50)),
                ('codigo_cliente', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('es_adicional', models.BooleanField(default=False)),
                ('codigo_vicaf', models.CharField(max_length=50, unique=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.categoriaservicio')),
            ],
        ),
        migrations.CreateModel(
            name='RecepcionMuestraLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.CharField(max_length=50, unique=True)),
                ('responsable_entrega', models.CharField(max_length=255)),
                ('telefono_entrega', models.CharField(blank=True, max_length=50)),
                ('fecha_recepcion', models.DateField()),
                ('hora_recepcion', models.TimeField()),
                ('fecha_muestreo', models.DateField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
                ('recepcionado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trabajadores.trabajadorprofile')),
            ],
        ),
        migrations.RemoveField(
            model_name='detalleensayo',
            name='detalle_cotizacion',
        ),
        migrations.RemoveField(
            model_name='detalleensayo',
            name='firma_tecnico',
        ),
        migrations.RemoveField(
            model_name='detalleensayo',
            name='metodo',
        ),
        migrations.RemoveField(
            model_name='detalleensayo',
            name='norma',
        ),
        migrations.RemoveField(
            model_name='detalleensayo',
            name='solicitud',
        ),
        migrations.RemoveField(
            model_name='detalleensayo',
            name='tipos_ensayo',
        ),
        migrations.RemoveField(
            model_name='documentofinal',
            name='proyecto',
        ),
        migrations.AlterUniqueTogether(
            name='ensayoparametro',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ensayoparametro',
            name='tipo_ensayo',
        ),
        migrations.RemoveField(
            model_name='muestra',
            name='id_lab',
        ),
        migrations.RemoveField(
            model_name='muestra',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='muestra',
            name='recepcionado_por',
        ),
        migrations.RemoveField(
            model_name='muestra',
            name='tecnico_responsable_muestra',
        ),
        migrations.RemoveField(
            model_name='muestra',
            name='tipo_muestra',
        ),
        migrations.RemoveField(
            model_name='muestra',
            name='tomada_por',
        ),
        migrations.RemoveField(
            model_name='reporteincidencia',
            name='responsable_laboratorio',
        ),
        migrations.RemoveField(
            model_name='reporteincidencia',
            name='solicitud',
        ),
        migrations.AlterUniqueTogether(
            name='resultadoensayo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='resultadoensayo',
            name='detalle_ensayo',
        ),
        migrations.RemoveField(
            model_name='resultadoensayo',
            name='metodo_aplicado',
        ),
        migrations.RemoveField(
            model_name='resultadoensayo',
            name='norma_aplicada',
        ),
        migrations.RemoveField(
            model_name='resultadoensayo',
            name='resultado_origen',
        ),
        migrations.RemoveField(
            model_name='resultadoensayo',
            name='supervisor_revisor',
        ),
        migrations.RemoveField(
            model_name='resultadoensayo',
            name='tecnico_ejecutor',
        ),
        migrations.RemoveField(
            model_name='resultadoensayo',
            name='tipo_ensayo',
        ),
        migrations.AlterUniqueTogether(
            name='resultadoensayovalor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='resultadoensayovalor',
            name='parametro',
        ),
        migrations.RemoveField(
            model_name='resultadoensayovalor',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='solicitudensayo',
            name='firma_jefe_laboratorio',
        ),
        migrations.RemoveField(
            model_name='solicitudensayo',
            name='generada_por',
        ),
        migrations.RemoveField(
            model_name='solicitudensayo',
            name='muestra',
        ),
        migrations.RemoveField(
            model_name='tipomuestra',
            name='tipo_laboratorio',
        ),
        migrations.DeleteModel(
            name='AsignacionTipoEnsayo',
        ),
        migrations.DeleteModel(
            name='DetalleEnsayo',
        ),
        migrations.DeleteModel(
            name='DocumentoFinal',
        ),
        migrations.DeleteModel(
            name='EnsayoParametro',
        ),
        migrations.DeleteModel(
            name='Laboratorio',
        ),
        migrations.DeleteModel(
            name='Muestra',
        ),
        migrations.DeleteModel(
            name='ReporteIncidencia',
        ),
        migrations.DeleteModel(
            name='ResultadoEnsayo',
        ),
        migrations.DeleteModel(
            name='ResultadoEnsayoValor',
        ),
        migrations.DeleteModel(
            name='SolicitudEnsayo',
        ),
        migrations.DeleteModel(
            name='TipoEnsayo',
        ),
        migrations.DeleteModel(
            name='TipoMuestra',
        ),
        migrations.AddField(
            model_name='muestraitem',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proyectos.recepcionmuestralote'),
        ),
        migrations.AddField(
            model_name='muestraitem',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='muestraitem',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.subcategoria'),
        ),
    ]
