# Generated by Django 4.2.25 on 2025-12-04 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomuestra',
            name='tipo_laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.laboratorio', verbose_name='Área de Laboratorio Asociada'),
        ),
    ]
