# Generated by Django 4.2.27 on 2026-02-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=5, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='recepcionmuestralote',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='recepcionmuestralote',
            name='recepcionado_por',
        ),
        migrations.DeleteModel(
            name='MuestraItem',
        ),
        migrations.DeleteModel(
            name='RecepcionMuestraLote',
        ),
    ]
