# Generated by Django 4.2.25 on 2025-10-22 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEnsayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Ensayo (Catálogo)')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Detallada')),
                ('codigo_interno', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código Interno')),
            ],
            options={
                'verbose_name': 'Tipo de Ensayo',
                'verbose_name_plural': 'Tipos de Ensayos',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='detalleensayo',
            name='tecnico_asignado',
        ),
        migrations.RemoveField(
            model_name='resultadoensayo',
            name='muestra',
        ),
        migrations.AlterField(
            model_name='solicitudensayo',
            name='codigo_solicitud',
            field=models.CharField(max_length=100, unique=True, verbose_name='Código de Solicitud/Orden'),
        ),
        migrations.CreateModel(
            name='AsignacionTipoEnsayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='proyectos.detalleensayo', verbose_name='Tarea de Detalle')),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_ensayos_asignados', to='trabajadores.trabajadorprofile', verbose_name='Técnico (Supervisor) Asignado')),
                ('tipo_ensayo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_tecnicos', to='proyectos.tipoensayo', verbose_name='Tipo de Ensayo a Ejecutar')),
            ],
            options={
                'verbose_name': 'Asignación de Ensayo a Técnico',
                'verbose_name_plural': 'Asignaciones de Ensayos a Técnicos',
                'unique_together': {('detalle', 'tipo_ensayo')},
            },
        ),
        migrations.AddField(
            model_name='detalleensayo',
            name='tipos_ensayo',
            field=models.ManyToManyField(related_name='detalles_con_asignacion', through='proyectos.AsignacionTipoEnsayo', to='proyectos.tipoensayo', verbose_name='Tipos de Ensayos Asignados'),
        ),
    ]
