# Generated by Django 4.2.27 on 2026-02-06 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_cotizacion_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0002_tipomuestra_remove_recepcionmuestralote_proyecto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedencia', models.CharField(max_length=255)),
                ('responsable_cliente', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_recepcion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fabricacion', models.DateField(blank=True, null=True)),
                ('fecha_muestreo', models.DateField(blank=True, null=True)),
                ('fecha_ensayo_programado', models.DateField(blank=True, null=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='servicios.cotizacion')),
                ('responsable_recepcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MuestraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('masa_aprox', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField(default=1)),
                ('unidad', models.CharField(default='UND', max_length=50)),
                ('codigo_laboratorio', models.CharField(blank=True, max_length=50, unique=True)),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras', to='proyectos.recepcionmuestra')),
                ('tipo_muestra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.tipomuestra')),
            ],
        ),
    ]
