# Generated by Django 4.2.25 on 2025-12-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_tipomuestra_tipo_laboratorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='codigo_lote_generado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Lote (V-TIPO-AÑO)'),
        ),
    ]
