# Generated by Django 4.2.25 on 2025-10-23 21:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
        ('trabajadores', '0001_initial'),
        ('proyectos', '0002_tipoensayo_remove_detalleensayo_tecnico_asignado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleensayo',
            options={'verbose_name': 'Detalle de Ensayo (Línea de Trabajo)', 'verbose_name_plural': 'Detalles de Ensayos (Líneas de Trabajo)'},
        ),
        migrations.RemoveField(
            model_name='detalleensayo',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='detalleensayo',
            name='detalle_cotizacion',
        ),
        migrations.RemoveField(
            model_name='detalleensayo',
            name='estado_detalle',
        ),
        migrations.RemoveField(
            model_name='detalleensayo',
            name='metodo_aplicable',
        ),
        migrations.RemoveField(
            model_name='detalleensayo',
            name='modificado_en',
        ),
        migrations.RemoveField(
            model_name='detalleensayo',
            name='norma_aplicable',
        ),
        migrations.AddField(
            model_name='detalleensayo',
            name='fecha_entrega_real',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Real (Técnico)'),
        ),
        migrations.AddField(
            model_name='detalleensayo',
            name='firma_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_firmados', to='trabajadores.trabajadorprofile', verbose_name='Firma del Técnico (Completado)'),
        ),
        migrations.AddField(
            model_name='detalleensayo',
            name='metodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.metodo', verbose_name='Método de Ensayo'),
        ),
        migrations.AddField(
            model_name='detalleensayo',
            name='norma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.norma', verbose_name='Norma de Ensayo'),
        ),
        migrations.AddField(
            model_name='detalleensayo',
            name='observaciones_detalle',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones de la Tarea/Ensayo'),
        ),
        migrations.AddField(
            model_name='solicitudensayo',
            name='cotizacion',
            field=models.ForeignKey(blank=True, help_text='Número de la cotización que originó el trabajo.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.cotizacion', verbose_name='No. Cotización'),
        ),
        migrations.AddField(
            model_name='solicitudensayo',
            name='fecha_entrega_programada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega de Registros (Programada)'),
        ),
        migrations.AddField(
            model_name='solicitudensayo',
            name='fecha_entrega_real',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Real de Entrega de Registros'),
        ),
        migrations.AddField(
            model_name='solicitudensayo',
            name='firma_jefe_laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_firmadas', to='trabajadores.trabajadorprofile', verbose_name='Jefe de Laboratorio que Firma'),
        ),
        migrations.AlterField(
            model_name='detalleensayo',
            name='fecha_limite_ejecucion',
            field=models.DateField(verbose_name='Fecha Límite de Ejecución (Entrega Programada)'),
        ),
        migrations.AlterField(
            model_name='solicitudensayo',
            name='estado',
            field=models.CharField(choices=[('ASIGNADA', 'Técnicos Asignados'), ('EN_ANALISIS', 'En Curso'), ('COMPLETADA', 'Todos los Ensayos Finalizados'), ('CERRADA', 'Cerrada con Informe')], default='ASIGNADA', max_length=30, verbose_name='Estado de la Solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitudensayo',
            name='generada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_generadas', to='trabajadores.trabajadorprofile', verbose_name='Persona que Elabora la Solicitud'),
        ),
        migrations.CreateModel(
            name='ReporteIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_incidencia', models.CharField(choices=[('CAMBIO', 'Cambio en Solicitud/Alcance'), ('ANULACION', 'Anulación de Ensayo/Detalle'), ('INCREMENTO', 'Incremento de Ensayos'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Tipo de Incidencia')),
                ('detalle_incidencia', models.TextField(verbose_name='Detalle de la Incidencia')),
                ('fecha_ocurrencia', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Ocurrencia')),
                ('representante_cliente', models.CharField(max_length=150, verbose_name='Representante del Cliente (Nombre/Firma)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('responsable_laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_registradas', to='trabajadores.trabajadorprofile', verbose_name='Responsable del Laboratorio (Jefe/Supervisor)')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='proyectos.solicitudensayo', verbose_name='Solicitud de Ensayo Asociada')),
            ],
            options={
                'verbose_name': 'Reporte de Incidencia',
                'verbose_name_plural': 'Reportes de Incidencias',
                'ordering': ['-fecha_ocurrencia'],
            },
        ),
    ]
