# Generated by Django 4.2.25 on 2025-12-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_muestra_codigo_lote_generado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Inicio'), ('EN_CURSO', 'En Curso'), ('MUESTRAS_ASIGNADAS', 'Técnicos Asignados'), ('MUESTRAS_VALIDADAS', 'Muestras Validadas (Listo para Informe)'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado del Proyecto'),
        ),
        migrations.AlterField(
            model_name='solicitudensayo',
            name='codigo_solicitud',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código de Solicitud/Orden'),
        ),
    ]
