# Generated by Django 4.2.25 on 2025-10-24 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
        ('proyectos', '0003_alter_detalleensayo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleensayo',
            name='detalle_cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.cotizaciondetalle', verbose_name='Detalle de Cotización de Origen'),
        ),
        migrations.AddField(
            model_name='detalleensayo',
            name='estado_detalle',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Asignación'), ('ASIGNADO', 'Asignado a Técnico'), ('EN_EJECUCION', 'En Ejecución'), ('COMPLETADO', 'Completado por Técnico'), ('VALIDADO', 'Validado por Supervisor')], default='PENDIENTE', max_length=20, verbose_name='Estado del Detalle de Ensayo'),
        ),
    ]
