# Generated by Django 4.2.27 on 2026-02-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_recepcionmuestra_muestradetalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipomuestra',
            name='descripcion',
        ),
    ]
