# Generated by Django 4.2.25 on 2025-10-24 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_detalleensayo_detalle_cotizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudensayo',
            name='cotizacion',
        ),
    ]
