# Generated by Django 4.2.27 on 2026-02-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_remove_tipomuestra_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestradetalle',
            name='nro_item',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='muestradetalle',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
