# Generated by Django 4.2.25 on 2025-12-20 16:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
        ('trabajadores', '0001_initial'),
        ('proyectos', '0004_alter_proyecto_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnsayoParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Parámetro')),
                ('unidad', models.CharField(blank=True, max_length=30, null=True, verbose_name='Unidad (MPa, %, g/cm3, etc.)')),
                ('es_numerico', models.BooleanField(default=True, verbose_name='¿Valor Numérico?')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden de Visualización')),
                ('tipo_ensayo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='proyectos.tipoensayo', verbose_name='Tipo de Ensayo')),
            ],
            options={
                'verbose_name': 'Parámetro de Ensayo',
                'verbose_name_plural': 'Parámetros de Ensayo',
                'ordering': ('orden',),
                'unique_together': {('tipo_ensayo', 'nombre')},
            },
        ),
        migrations.AlterModelOptions(
            name='resultadoensayo',
            options={'ordering': ['-fecha_inicio_ensayo'], 'verbose_name': 'Resultado de Ensayo', 'verbose_name_plural': 'Resultados de Ensayos'},
        ),
        migrations.AddField(
            model_name='resultadoensayo',
            name='datos_crudos',
            field=models.JSONField(blank=True, null=True, verbose_name='Datos Crudos / Curvas / Registros de Equipo'),
        ),
        migrations.AddField(
            model_name='resultadoensayo',
            name='es_reensayo',
            field=models.BooleanField(default=False, verbose_name='¿Es Reensayo?'),
        ),
        migrations.AddField(
            model_name='resultadoensayo',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado por Técnico'), ('VALIDADO', 'Validado por Supervisor'), ('APROBADO', 'Aprobado para Informe'), ('OBSERVADO', 'Observado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20, verbose_name='Estado del Resultado'),
        ),
        migrations.AddField(
            model_name='resultadoensayo',
            name='fecha_fin_ensayo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización del Ensayo'),
        ),
        migrations.AddField(
            model_name='resultadoensayo',
            name='fecha_inicio_ensayo',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio del Ensayo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadoensayo',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 20, 16, 0, 59, 632831, tzinfo=datetime.timezone.utc), verbose_name='Fecha de Registro en el Sistema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadoensayo',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión / Validación'),
        ),
        migrations.AddField(
            model_name='resultadoensayo',
            name='metodo_aplicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.metodo', verbose_name='Método de Ensayo'),
        ),
        migrations.AddField(
            model_name='resultadoensayo',
            name='norma_aplicada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.norma', verbose_name='Norma Aplicada'),
        ),
        migrations.AddField(
            model_name='resultadoensayo',
            name='observaciones_revision',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones de Revisión / Supervisor'),
        ),
        migrations.AddField(
            model_name='resultadoensayo',
            name='observaciones_tecnicas',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Técnicas del Ensayo'),
        ),
        migrations.AddField(
            model_name='resultadoensayo',
            name='resultado_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reensayos', to='proyectos.resultadoensayo', verbose_name='Resultado Original (si es reensayo)'),
        ),
        migrations.AddField(
            model_name='resultadoensayo',
            name='supervisor_revisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_revisados', to='trabajadores.trabajadorprofile', verbose_name='Supervisor Revisor'),
        ),
        migrations.AddField(
            model_name='resultadoensayo',
            name='tecnico_ejecutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_ejecutados', to='trabajadores.trabajadorprofile', verbose_name='Técnico Ejecutor'),
        ),
        migrations.AddField(
            model_name='resultadoensayo',
            name='tipo_ensayo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='proyectos.tipoensayo', verbose_name='Tipo de Ensayo Ejecutado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultadoensayo',
            name='detalle_ensayo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='proyectos.detalleensayo', verbose_name='Detalle de Ensayo (Tarea)'),
        ),
        migrations.AlterUniqueTogether(
            name='resultadoensayo',
            unique_together={('detalle_ensayo', 'tipo_ensayo')},
        ),
        migrations.RemoveField(
            model_name='resultadoensayo',
            name='es_valido',
        ),
        migrations.RemoveField(
            model_name='resultadoensayo',
            name='fecha_realizacion',
        ),
        migrations.RemoveField(
            model_name='resultadoensayo',
            name='fecha_verificacion',
        ),
        migrations.RemoveField(
            model_name='resultadoensayo',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='resultadoensayo',
            name='resultados_data',
        ),
        migrations.RemoveField(
            model_name='resultadoensayo',
            name='tecnico_registro',
        ),
        migrations.RemoveField(
            model_name='resultadoensayo',
            name='verificado_por',
        ),
        migrations.CreateModel(
            name='ResultadoEnsayoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='Valor Numérico')),
                ('valor_texto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor Textual / Cualitativo')),
                ('cumple', models.BooleanField(blank=True, null=True, verbose_name='¿Cumple Especificación?')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.ensayoparametro', verbose_name='Parámetro Medido')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='proyectos.resultadoensayo', verbose_name='Resultado de Ensayo')),
            ],
            options={
                'verbose_name': 'Valor del Resultado',
                'verbose_name_plural': 'Valores de Resultados',
                'unique_together': {('resultado', 'parametro')},
            },
        ),
    ]
