# Generated by Django 4.2.25 on 2025-12-27 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_ensayoparametro_alter_resultadoensayo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentofinal',
            options={},
        ),
        migrations.RemoveField(
            model_name='documentofinal',
            name='analisis_detallado_ia',
        ),
        migrations.RemoveField(
            model_name='documentofinal',
            name='archivo_original',
        ),
        migrations.RemoveField(
            model_name='documentofinal',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='documentofinal',
            name='firma_cliente',
        ),
        migrations.RemoveField(
            model_name='documentofinal',
            name='firma_supervisor',
        ),
        migrations.RemoveField(
            model_name='documentofinal',
            name='modificado_en',
        ),
        migrations.RemoveField(
            model_name='documentofinal',
            name='recomendaciones_ia',
        ),
        migrations.RemoveField(
            model_name='documentofinal',
            name='resumen_ejecutivo_ia',
        ),
        migrations.AddField(
            model_name='documentofinal',
            name='archivo_pdf',
            field=models.FileField(default='', upload_to='informes_finales/%Y/%m/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentofinal',
            name='publicado',
            field=models.BooleanField(default=False, help_text='Si está marcado, el cliente puede verlo.'),
        ),
        migrations.AlterField(
            model_name='documentofinal',
            name='fecha_emision',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='documentofinal',
            name='proyecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documento_final', to='proyectos.proyecto'),
        ),
        migrations.AlterField(
            model_name='documentofinal',
            name='titulo',
            field=models.CharField(default='Informe Técnico Final', max_length=255),
        ),
    ]
