# Generated by Django 4.2.27 on 2026-02-21 15:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_cotizacion_estado'),
        ('trabajadores', '0001_initial'),
        ('proyectos', '0005_muestradetalle_nro_item_muestradetalle_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudEnsayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_solicitud', models.CharField(max_length=50, unique=True, verbose_name='No. DE SOLICITUD')),
                ('fecha_solicitud', models.DateField(default=django.utils.timezone.now, verbose_name='FECHA DE SOLICITUD')),
                ('fecha_entrega_programada', models.DateField(verbose_name='FECHA DE ENTREGA DE REGISTROS (PROGRAMADA)')),
                ('fecha_entrega_real', models.DateField(blank=True, null=True, verbose_name='FECHA REAL DE ENTREGA DE REGISTROS')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_ensayo', to='servicios.cotizacion', verbose_name='No. COTIZACIÓN')),
                ('elaborado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_elaboradas', to='trabajadores.trabajadorprofile', verbose_name='PERSONA QUE ELABORA LA SOLICITUD')),
                ('recepcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_ensayo', to='proyectos.recepcionmuestra', verbose_name='Recepción Asociada')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to='trabajadores.trabajadorprofile', verbose_name='FIRMA JEFE DE LABORATORIO')),
            ],
            options={
                'verbose_name': 'Solicitud de Ensayo',
                'verbose_name_plural': 'Solicitudes de Ensayo',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='IncidenciaSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_incidencia', models.TextField(verbose_name='Detalle de incidencia')),
                ('fecha_ocurrencia', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de ocurrencia')),
                ('representante_cliente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Representante del Cliente')),
                ('representante_laboratorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trabajadores.trabajadorprofile', verbose_name='Representante del Laboratorio')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='proyectos.solicitudensayo')),
            ],
            options={
                'verbose_name': 'Incidencia de Solicitud',
                'verbose_name_plural': 'Incidencias de Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicitudEnsayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_ensayo', models.CharField(max_length=255, verbose_name='Descripción')),
                ('norma', models.CharField(max_length=255, verbose_name='Norma de ensayo')),
                ('metodo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Método')),
                ('fecha_entrega_programada', models.DateField(verbose_name='Entrega Programada')),
                ('fecha_entrega_real', models.DateField(blank=True, null=True, verbose_name='Entrega Real')),
                ('aceptado_tecnico', models.BooleanField(default=False, help_text='Check para reemplazar la firma manual del técnico', verbose_name='Aceptación (Firma)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.muestradetalle', verbose_name='Código de Muestra (Lab)')),
                ('servicio_cotizado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.cotizaciondetalle', verbose_name='Servicio/Ensayo')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='proyectos.solicitudensayo')),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trabajadores.trabajadorprofile', verbose_name='Técnico Asignado')),
            ],
            options={
                'verbose_name': 'Detalle de Solicitud',
                'verbose_name_plural': 'Detalles de Solicitudes',
            },
        ),
    ]
