# Generated by Django 4.2.27 on 2026-02-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_solicitudensayo_incidenciasolicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudensayo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'PENDIENTE'), ('proceso', 'EN PROCESO'), ('finalizado', 'FINALIZADO')], default='pendiente', max_length=20, verbose_name='ESTADO OPERATIVO'),
        ),
    ]
