# Generated by Django 4.2.27 on 2026-02-27 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
        ('proyectos', '0007_solicitudensayo_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidenciasolicitud',
            options={'ordering': ['fecha_ocurrencia'], 'verbose_name': 'Incidencia de Solicitud', 'verbose_name_plural': 'Incidencias de Solicitudes'},
        ),
        migrations.AddField(
            model_name='incidenciasolicitud',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_autorizadas', to='trabajadores.trabajadorprofile', verbose_name='Firma de Autorización'),
        ),
        migrations.AddField(
            model_name='incidenciasolicitud',
            name='esta_autorizada',
            field=models.BooleanField(default=False, help_text='Indica si la incidencia ha sido validada/firmada electrónicamente.', verbose_name='Autorizado'),
        ),
        migrations.AddField(
            model_name='incidenciasolicitud',
            name='fecha_autorizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Firma'),
        ),
        migrations.AlterField(
            model_name='incidenciasolicitud',
            name='detalle_incidencia',
            field=models.TextField(verbose_name='Detalle de la incidencia'),
        ),
        migrations.AlterField(
            model_name='incidenciasolicitud',
            name='representante_laboratorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_responsable', to='trabajadores.trabajadorprofile', verbose_name='Responsable del laboratorio (JL / SL)'),
        ),
    ]
