# Generated by Django 4.2.27 on 2026-02-28 23:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
        ('proyectos', '0008_alter_incidenciasolicitud_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_informe', models.CharField(editable=False, max_length=50, unique=True)),
                ('archivo_pdf', models.FileField(upload_to='informes_finales/pdfs/%Y/%m/')),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug_validacion', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='informes_finales/qrs/')),
                ('descargas_count', models.PositiveIntegerField(default=0)),
                ('responsable_firma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes_firmados', to='trabajadores.trabajadorprofile')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informe_final', to='proyectos.solicitudensayo')),
            ],
            options={
                'verbose_name': 'Informe Final',
                'verbose_name_plural': 'Informes Finales',
            },
        ),
    ]
