# Generated by Django 4.2.27 on 2026-03-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0009_informefinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='informefinal',
            name='estado_envio',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Envío'), ('enviado', 'Enviado al Cliente')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='informefinal',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
