# Generated by Django 4.2.29 on 2026-08-24 02:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("web_catalogo", "0001_initial"),
        ("servicios", "0006_alter_servicio_nombre"),
        ("clientes", "0002_cliente_origen"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web_zonas", "0002_seed_zonas"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitudCotizacionWeb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ruc",
                    models.CharField(
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{11}$", "El RUC debe tener 11 dígitos numéricos."
                            )
                        ],
                    ),
                ),
                ("razon_social", models.CharField(max_length=255)),
                ("persona_contacto", models.CharField(max_length=200)),
                ("correo_contacto", models.EmailField(max_length=254)),
                ("telefono_contacto", models.CharField(max_length=20)),
                (
                    "necesidad",
                    models.TextField(
                        help_text="Descripción libre de la necesidad del visitante."
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        blank=True,
                        help_text="Ruta de la página que generó la solicitud (para saber qué keyword convierte).",
                        max_length=255,
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_web",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "cotizacion",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitud_web",
                        to="servicios.cotizacion",
                    ),
                ),
                (
                    "zona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_cotizacion",
                        to="web_zonas.zonacobertura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de cotización web",
                "verbose_name_plural": "Solicitudes de cotización web",
                "ordering": ["-creado"],
            },
        ),
        migrations.CreateModel(
            name="SolicitudCotizacionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_estimada",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "servicio_publicado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="web_catalogo.serviciopublicado",
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="web_contacto.solicitudcotizacionweb",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de solicitud de cotización web",
                "verbose_name_plural": "Ítems de solicitud de cotización web",
            },
        ),
        migrations.CreateModel(
            name="MensajeContacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("correo", models.EmailField(max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("asunto", models.CharField(max_length=150)),
                ("mensaje", models.TextField()),
                (
                    "origen",
                    models.CharField(
                        blank=True,
                        help_text="Ruta de la página que generó el contacto (para saber qué keyword convierte).",
                        max_length=255,
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("nuevo", "Nuevo"),
                            ("atendido", "Atendido"),
                            ("cerrado", "Cerrado"),
                        ],
                        default="nuevo",
                        max_length=10,
                    ),
                ),
                ("fecha_atencion", models.DateTimeField(blank=True, null=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "atendido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mensajes_contacto_atendidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de contacto",
                "verbose_name_plural": "Mensajes de contacto",
                "ordering": ["-creado"],
            },
        ),
    ]
