# Generated by Django 4.2.29 on 2026-08-23 16:38

from django.db import migrations, models
import django.db.models.deletion
import grupovicaf.seo


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("trabajadores", "0006_alter_permisomodulo_options_and_more"),
        ("servicios", "0006_alter_servicio_nombre"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicioPublicado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Si se deja en blanco, se usa el título natural de la página.",
                        max_length=60,
                        validators=[grupovicaf.seo.validar_meta_title],
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        validators=[grupovicaf.seo.validar_meta_description],
                    ),
                ),
                ("noindex", models.BooleanField(default=False)),
                ("imagen_og", models.ImageField(blank=True, upload_to="seo/og/")),
                (
                    "titulo_publico",
                    models.CharField(
                        help_text='Nombre comercial, no el código interno. Ej: "Ensayo CBR".',
                        max_length=150,
                    ),
                ),
                (
                    "resumen",
                    models.CharField(
                        help_text="Para listados y como meta description.",
                        max_length=300,
                    ),
                ),
                (
                    "contenido",
                    models.TextField(
                        help_text="Página completa del ensayo (600-1000 palabras)."
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(blank=True, upload_to="catalogo/servicios/"),
                ),
                (
                    "imagen_alt",
                    models.CharField(
                        blank=True,
                        help_text="Obligatorio si se sube imagen: describe la escena para accesibilidad y SEO.",
                        max_length=125,
                    ),
                ),
                (
                    "zona_principal",
                    models.CharField(
                        default="Cajamarca",
                        help_text='Ciudad usada en el H1 ("Ensayo CBR en Cajamarca"). Sin enlace a landing de zona todavía: web_zonas no existe.',
                        max_length=100,
                    ),
                ),
                ("destacado", models.BooleanField(default=False)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="servicios_publicados",
                        to="servicios.categoriaservicio",
                    ),
                ),
                (
                    "servicio",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publicado",
                        to="servicios.servicio",
                    ),
                ),
                (
                    "subcategoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="servicios_publicados",
                        to="servicios.subcategoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio publicado",
                "verbose_name_plural": "Servicios publicados",
                "ordering": [
                    "categoria__nombre",
                    "subcategoria__nombre",
                    "orden",
                    "titulo_publico",
                ],
            },
        ),
        migrations.CreateModel(
            name="PreguntaFrecuente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pregunta", models.CharField(max_length=255)),
                ("respuesta", models.TextField()),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                (
                    "servicio_publicado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preguntas",
                        to="web_catalogo.serviciopublicado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta frecuente",
                "verbose_name_plural": "Preguntas frecuentes",
                "ordering": ["orden", "id"],
            },
        ),
        migrations.CreateModel(
            name="MiembroEquipoPublicado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio_publica",
                    models.TextField(
                        blank=True,
                        help_text="Biografía corta para la web. Nunca datos internos.",
                    ),
                ),
                ("mostrar_correo", models.BooleanField(default=False)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "perfil",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publicado",
                        to="trabajadores.trabajadorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Miembro de equipo publicado",
                "verbose_name_plural": "Miembros de equipo publicados",
                "ordering": ["orden", "id"],
            },
        ),
        migrations.CreateModel(
            name="ClienteDestacado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mostrar_logo", models.BooleanField(default=True)),
                (
                    "enlace",
                    models.URLField(
                        blank=True, help_text="Sitio web del cliente (opcional)."
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destacado",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente destacado",
                "verbose_name_plural": "Clientes destacados",
                "ordering": ["orden", "id"],
            },
        ),
    ]
