# Generated by Django 4.2.29 on 2026-08-31 04:04

from django.db import migrations, models
import django.db.models.deletion
import grupovicaf.seo


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_alter_servicio_nombre'),
        ('web_catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('meta_title', models.CharField(blank=True, help_text='Si se deja en blanco, se usa el título natural de la página.', max_length=60, validators=[grupovicaf.seo.validar_meta_title])),
                ('meta_description', models.CharField(blank=True, max_length=160, validators=[grupovicaf.seo.validar_meta_description])),
                ('noindex', models.BooleanField(default=False)),
                ('imagen_og', models.ImageField(blank=True, upload_to='seo/og/')),
                ('nombre', models.CharField(help_text='Ej: "Mecánica de Suelos".', max_length=100)),
                ('titulo_h1', models.CharField(help_text='H1 de la página. Ej: "Mecánica de suelos y estudios geotécnicos en Cajamarca".', max_length=150)),
                ('resumen', models.CharField(help_text='Una o dos líneas, para la tarjeta del índice.', max_length=300)),
                ('contenido', models.TextField(help_text='Texto comercial de la página de línea. Redacción única (ver CLAUDE.md regla 16).')),
                ('imagen', models.ImageField(blank=True, upload_to='catalogo/lineas/')),
                ('imagen_alt', models.CharField(blank=True, help_text='Obligatorio si se sube imagen: describe la escena para accesibilidad y SEO.', max_length=125)),
                ('icono', models.CharField(blank=True, help_text='Nombre de ícono opcional para la tarjeta del índice (uso libre en la plantilla).', max_length=50)),
                ('destacado', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('ensayos', models.ManyToManyField(blank=True, help_text='Ensayos del LIMS que agrupa esta línea comercial.', related_name='lineas_servicio', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Línea de servicio',
                'verbose_name_plural': 'Líneas de servicio',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='serviciopublicado',
            name='linea',
            field=models.ForeignKey(blank=True, help_text='Línea comercial a la que pertenece este ensayo (ej. "Mecánica de Suelos"). Opcional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ensayos_publicados', to='web_catalogo.lineaservicio'),
        ),
    ]
