# Generated by Django 4.2.29 on 2026-08-31 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_catalogo', '0003_seed_lineas_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(height_field='alto', upload_to='catalogo/lineas/galeria/', width_field='ancho')),
                ('ancho', models.PositiveIntegerField(default=0, editable=False)),
                ('alto', models.PositiveIntegerField(default=0, editable=False)),
                ('alt_text', models.CharField(help_text='Obligatorio: describe la escena para accesibilidad y SEO.', max_length=125)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='web_catalogo.lineaservicio')),
            ],
            options={
                'verbose_name': 'Imagen de línea',
                'verbose_name_plural': 'Imágenes de línea',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
