# Generated by Django 4.2.29 on 2026-08-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_catalogo', '0005_infohtml_y_galeria_lineas'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenlinea',
            name='alto_miniatura',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='imagenlinea',
            name='ancho_miniatura',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='imagenlinea',
            name='imagen_miniatura',
            field=models.ImageField(blank=True, editable=False, height_field='alto_miniatura', help_text='Se genera sola a partir de "imagen" al guardar (ver save()).', upload_to='catalogo/lineas/galeria/miniaturas/', width_field='ancho_miniatura'),
        ),
        migrations.AlterField(
            model_name='imagenlinea',
            name='imagen',
            field=models.ImageField(height_field='alto', help_text='Foto completa: se usa en el lightbox al ampliar.', upload_to='catalogo/lineas/galeria/', width_field='ancho'),
        ),
    ]
