# Generated by Django 4.2.29 on 2026-09-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_catalogo', '0008_imagenes_mezclas_equipos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciopublicado',
            name='zona_principal',
            field=models.CharField(default='Cajamarca', help_text='Ciudad usada en el H1 ("Ensayo CBR en Cajamarca").', max_length=100),
        ),
    ]
