# Generated by Django 4.2.29 on 2026-08-24 00:37

from django.db import migrations, models
import grupovicaf.seo


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("web_catalogo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZonaCobertura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Si se deja en blanco, se usa el título natural de la página.",
                        max_length=60,
                        validators=[grupovicaf.seo.validar_meta_title],
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        validators=[grupovicaf.seo.validar_meta_description],
                    ),
                ),
                ("noindex", models.BooleanField(default=False)),
                ("imagen_og", models.ImageField(blank=True, upload_to="seo/og/")),
                ("nombre", models.CharField(help_text='Ej: "Jaén".', max_length=100)),
                ("provincia", models.CharField(max_length=100)),
                ("departamento", models.CharField(default="Cajamarca", max_length=100)),
                (
                    "titulo_h1",
                    models.CharField(
                        help_text='H1 de la página. Ej: "Laboratorio de suelos en Jaén".',
                        max_length=150,
                    ),
                ),
                (
                    "introduccion",
                    models.TextField(
                        help_text="Párrafo de entrada (1-2 líneas), redacción única de esta zona."
                    ),
                ),
                (
                    "contenido",
                    models.TextField(
                        help_text="Redacción única de esta zona (no reutilizar entre zonas). Debe incluir: proyectos reales ejecutados en la zona, tiempos de respuesta típicos, cómo se envían las muestras desde ahí hacia el laboratorio, y referencias locales (vías de acceso, obras conocidas, gremios). Ver CLAUDE.md regla 16."
                    ),
                ),
                (
                    "latitud",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitud",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "es_sede",
                    models.BooleanField(
                        default=False,
                        help_text="Marca la sede física del laboratorio (Cajamarca). Las demás son cobertura.",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "servicios",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Ensayos disponibles para esta zona. El listado se genera automáticamente.",
                        related_name="zonas",
                        to="web_catalogo.serviciopublicado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zona de cobertura",
                "verbose_name_plural": "Zonas de cobertura",
                "ordering": ["-es_sede", "orden", "nombre"],
            },
        ),
    ]
