# Generated by Django 4.2.29 on 2026-03-26 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0001_initial'),
        ('clientes', '0001_initial'),
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('MANUAL', 'Manual'), ('SISTEMA', 'Generada por el sistema')], default='MANUAL', max_length=20, verbose_name='Origen')),
                ('clase', models.CharField(choices=[('REUNION', 'Reunión'), ('LLAMADA', 'Llamada'), ('VISITA', 'Visita'), ('RECEPCION', 'Recepción de Muestras'), ('ENSAYO', 'Ensayo'), ('ENTREGA', 'Entrega'), ('INFORME', 'Informe'), ('SEGUIMIENTO', 'Seguimiento'), ('MANTENIMIENTO', 'Mantenimiento'), ('CAPACITACION', 'Capacitación'), ('AUDITORIA', 'Auditoría'), ('INTERNO', 'Actividad Interna'), ('BLOQUEO', 'Bloqueo de Agenda'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Clase de actividad')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_CURSO', 'En Curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('REPROGRAMADA', 'Reprogramada'), ('VENCIDA', 'Vencida')], default='PROGRAMADA', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fin')),
                ('todo_el_dia', models.BooleanField(default=False, verbose_name='Todo el día')),
                ('bloquea_agenda', models.BooleanField(default=False, verbose_name='Bloquea agenda')),
                ('es_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('es_automatica', models.BooleanField(default=False, verbose_name='Automática')),
                ('permite_edicion_manual', models.BooleanField(default=True, verbose_name='Permite edición manual')),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación')),
                ('enlace_externo', models.URLField(blank=True, null=True, verbose_name='Enlace externo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones internas')),
                ('fecha_completada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha completada')),
                ('fecha_cancelada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha cancelada')),
                ('origen_modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Origen del sistema')),
                ('origen_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de origen')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_calendario_actualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Actividad de Calendario',
                'verbose_name_plural': 'Actividades de Calendario',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CalendarioCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#2563eb', max_length=20)),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Calendario',
                'verbose_name_plural': 'Categorías de Calendario',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CalendarioRecordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos_antes', models.PositiveIntegerField(verbose_name='Minutos antes')),
                ('tipo', models.CharField(choices=[('APP', 'Notificación interna'), ('EMAIL', 'Correo')], default='APP', max_length=20)),
                ('enviado', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='actividades.calendarioactividad')),
            ],
            options={
                'verbose_name': 'Recordatorio de Actividad',
                'verbose_name_plural': 'Recordatorios de Actividades',
                'ordering': ['minutos_antes'],
            },
        ),
        migrations.AddField(
            model_name='calendarioactividad',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='actividades.calendariocategoria', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='calendarioactividad',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_calendario', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='calendarioactividad',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades_calendario_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='calendarioactividad',
            name='informe_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_calendario', to='proyectos.informefinal', verbose_name='Informe final'),
        ),
        migrations.AddField(
            model_name='calendarioactividad',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_calendario', to='proyectos.proyecto', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='calendarioactividad',
            name='recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_calendario', to='proyectos.recepcionmuestra', verbose_name='Recepción'),
        ),
        migrations.AddField(
            model_name='calendarioactividad',
            name='solicitud_ensayo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_calendario', to='proyectos.solicitudensayo', verbose_name='Solicitud de ensayo'),
        ),
        migrations.CreateModel(
            name='CalendarioParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('RESPONSABLE', 'Responsable'), ('APOYO', 'Apoyo'), ('INVITADO', 'Invitado'), ('SUPERVISOR', 'Supervisor')], default='RESPONSABLE', max_length=20)),
                ('confirmado', models.BooleanField(default=False)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='actividades.calendarioactividad')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_calendario', to='trabajadores.trabajadorprofile')),
            ],
            options={
                'verbose_name': 'Participante de Actividad',
                'verbose_name_plural': 'Participantes de Actividades',
                'unique_together': {('actividad', 'trabajador')},
            },
        ),
        migrations.AddIndex(
            model_name='calendarioactividad',
            index=models.Index(fields=['fecha_inicio'], name='actividades_fecha_i_d7f8f5_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarioactividad',
            index=models.Index(fields=['fecha_fin'], name='actividades_fecha_f_df0dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarioactividad',
            index=models.Index(fields=['estado'], name='actividades_estado_1b558b_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarioactividad',
            index=models.Index(fields=['tipo'], name='actividades_tipo_0502e6_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarioactividad',
            index=models.Index(fields=['clase'], name='actividades_clase_8015e2_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarioactividad',
            index=models.Index(fields=['prioridad'], name='actividades_priorid_d9b868_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarioactividad',
            index=models.Index(fields=['proyecto'], name='actividades_proyect_ee1b01_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarioactividad',
            index=models.Index(fields=['solicitud_ensayo'], name='actividades_solicit_36b258_idx'),
        ),
    ]
