# Generated by Django 4.2.29 on 2026-04-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarioactividad',
            name='cliente_nombre_manual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cliente manual'),
        ),
    ]
