# Generated by Django 4.2.29 on 2026-08-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarruselInicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("imagen", models.ImageField(upload_to="inicio/carrusel/")),
                (
                    "alt_text",
                    models.CharField(
                        help_text="Describe la escena para accesibilidad y SEO de imagen. Obligatorio.",
                        max_length=125,
                        verbose_name="Texto alternativo",
                    ),
                ),
                ("enlace", models.URLField(blank=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                (
                    "fecha_inicio",
                    models.DateTimeField(
                        blank=True,
                        help_text="Si se define, el slide no se muestra antes de esta fecha.",
                        null=True,
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateTimeField(
                        blank=True,
                        help_text="Si se define, el slide deja de mostrarse después de esta fecha.",
                        null=True,
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Slide del carrusel",
                "verbose_name_plural": "Carrusel de inicio",
                "ordering": ["orden", "-creado"],
            },
        ),
    ]
