# Generated by Django 4.2.25 on 2025-10-22 01:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_oferta', models.CharField(max_length=50, unique=True, verbose_name='Número de Oferta (VCF-OTE-YYYY-XXX)')),
                ('asunto_servicio', models.CharField(max_length=255, verbose_name='Asunto del Servicio (Ej: Ensayos de Campo)')),
                ('proyecto_asociado', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia/Nombre del Proyecto del Cliente')),
                ('persona_contacto', models.CharField(max_length=200, verbose_name='Persona de Contacto (Atención)')),
                ('correo_contacto', models.EmailField(max_length=254, verbose_name='Correo de Contacto')),
                ('telefono_contacto', models.CharField(max_length=20, verbose_name='Teléfono de Contacto')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de Revisión Interna'), ('Enviada', 'Enviada al Cliente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Anulada', 'Anulada')], default='Pendiente', max_length=20, verbose_name='Estado de la Oferta')),
                ('aprobada_por_cliente', models.BooleanField(default=False, verbose_name='Aprobación Final del Cliente')),
                ('plazo_entrega_dias', models.IntegerField(default=30, verbose_name='Plazo de Entrega (Días)')),
                ('forma_pago', models.CharField(choices=[('Contado', 'Al Contado'), ('15_dias', 'A 15 días'), ('30_dias', 'A 30 días'), ('60_dias', 'A 60 días'), ('Personalizado', 'Personalizado')], default='Contado', max_length=20, verbose_name='Forma de Pago')),
                ('validez_oferta_dias', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Validez de la Oferta (Días)')),
                ('tasa_igv', models.DecimalField(decimal_places=3, default=0.18, max_digits=5, verbose_name='Tasa IGV Aplicada (Ej: 0.18)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal (Sin IGV)')),
                ('impuesto_igv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto IGV')),
                ('monto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Total (Final)')),
                ('observaciones_condiciones', models.TextField(blank=True, null=True, verbose_name='Observaciones o Condiciones Adicionales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='clientes.cliente', verbose_name='Cliente')),
                ('trabajador_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_emitidas', to='trabajadores.trabajadorprofile', verbose_name='Responsable de la Oferta')),
            ],
            options={
                'verbose_name': 'Cotización (Oferta Técnica)',
                'verbose_name_plural': 'Cotizaciones (Ofertas Técnicas)',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Metodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de Método (e.g., A/B, Ensayo)')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Método')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Método de Ensayo',
                'verbose_name_plural': 'Métodos de Ensayo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de Norma (e.g., ASTM D2216-19)')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre Completo de la Norma')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Norma de Ensayo',
                'verbose_name_plural': 'Normas de Ensayo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, verbose_name='Código de la Transacción/Voucher')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('imagen', models.FileField(upload_to='vouchers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])], verbose_name='Archivo (PDF/Imagen) del Voucher')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to='servicios.cotizacion', verbose_name='Cotización Asociada')),
            ],
            options={
                'verbose_name': 'Voucher de Pago',
                'verbose_name_plural': 'Vouchers de Pago',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_facturacion', models.CharField(max_length=50, unique=True, verbose_name='Cód. Fact. (e.g., ES001, TC001)')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Servicio/Ensayo')),
                ('descripcion', models.TextField(verbose_name='Descripción General del Servicio')),
                ('precio_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio Unitario Base')),
                ('unidad_base', models.CharField(default='Ensayo', max_length=50, verbose_name='Unidad de Medida Base')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/', verbose_name='Imagen Representativa')),
                ('esta_acreditado', models.BooleanField(default=False, verbose_name='¿Acreditado por INACAL-DA?')),
                ('metodos', models.ManyToManyField(blank=True, related_name='servicios', to='servicios.metodo', verbose_name='Métodos Asociados')),
                ('normas', models.ManyToManyField(blank=True, related_name='servicios', to='servicios.norma', verbose_name='Normas Asociadas')),
            ],
            options={
                'verbose_name': 'Servicio de Laboratorio',
                'verbose_name_plural': 'Servicios de Laboratorio',
                'ordering': ['nombre', 'codigo_facturacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título del Detalle')),
                ('descripcion', models.TextField(verbose_name='Descripción del Detalle')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/detalles/', verbose_name='Imagen o Ícono')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_web', to='servicios.servicio', verbose_name='Servicio Web')),
            ],
            options={
                'verbose_name': 'Detalle de Servicio (Página Web)',
                'verbose_name_plural': 'Detalles de Servicios (Página Web)',
            },
        ),
        migrations.CreateModel(
            name='CotizacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_especifica', models.TextField(verbose_name='Descripción del Ítem (Incluye notas específicas)')),
                ('unidad_medida', models.CharField(default='Ensayo', max_length=50, verbose_name='Unidad de Medida (Ej: Und, Ensayo, DM)')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario Acordado')),
                ('total_detalle', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Subtotal de Línea')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_cotizacion', to='servicios.cotizacion', verbose_name='Cotización Padre')),
                ('metodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.metodo', verbose_name='Método Aplicado')),
                ('norma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.norma', verbose_name='Norma de Ensayo Aplicada')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servicios.servicio', verbose_name='Servicio (Ensayo) Cotizado')),
            ],
            options={
                'verbose_name': 'Detalle de Cotización',
                'verbose_name_plural': 'Detalles de Cotización',
                'ordering': ['id'],
            },
        ),
    ]
