# Generated by Django 4.2.27 on 2026-01-31 20:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Categoría')),
            ],
            options={
                'verbose_name': '1. Categoría Principal',
                'verbose_name_plural': '1. Categorías Principales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_oferta', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de Oferta (VCF-OTE-YYYY-XXX)')),
                ('fecha_generacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Generación')),
                ('asunto_servicio', models.CharField(max_length=255, verbose_name='Asunto del Servicio (Ej: Ensayos de Campo)')),
                ('proyecto_asociado', models.CharField(blank=True, max_length=255, null=True, verbose_name='Proyecto del Cliente')),
                ('persona_contacto', models.CharField(max_length=200, verbose_name='Persona de Contacto (Atención)')),
                ('correo_contacto', models.EmailField(max_length=254, verbose_name='Correo de Contacto')),
                ('telefono_contacto', models.CharField(max_length=20, verbose_name='Teléfono de Contacto')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de Revisión'), ('Enviada', 'Enviada al Cliente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Anulada', 'Anulada')], default='Pendiente', max_length=20, verbose_name='Estado')),
                ('plazo_entrega_dias', models.IntegerField(default=30, verbose_name='Plazo de Entrega (Días)')),
                ('forma_pago', models.CharField(choices=[('Contado', 'Al Contado'), ('15_dias', 'A 15 días'), ('30_dias', 'A 30 días'), ('60_dias', 'A 60 días'), ('Personalizado', 'Personalizado')], default='Contado', max_length=20, verbose_name='Forma de Pago')),
                ('validez_oferta_dias', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Validez de la Oferta (Días)')),
                ('tasa_igv', models.DecimalField(decimal_places=3, default=0.18, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('impuesto_igv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('monto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('observaciones_condiciones', models.TextField(blank=True, null=True, verbose_name='Observaciones Adicionales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='clientes.cliente', verbose_name='Cliente')),
                ('servicio_general', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.categoriaservicio', verbose_name='Categoría General')),
                ('trabajador_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_emitidas', to='trabajadores.trabajadorprofile', verbose_name='Responsable de la Oferta')),
            ],
            options={
                'verbose_name': 'Cotización',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Metodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de Método')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Método')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Método de Ensayo',
                'verbose_name_plural': 'Métodos de Ensayo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de Norma')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre Completo')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Norma de Ensayo',
                'verbose_name_plural': 'Normas de Ensayo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Subcategoría')),
            ],
            options={
                'verbose_name': '2. Subcategoría',
                'verbose_name_plural': '2. Subcategorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, verbose_name='Código de la Transacción/Voucher')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('imagen', models.FileField(upload_to='vouchers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])], verbose_name='Archivo (PDF/Imagen) del Voucher')),
                ('documento_firmado', models.FileField(blank=True, null=True, upload_to='vouchers/documentos_firmados/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Oferta/Contrato Firmado por Cliente')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to='servicios.cotizacion', verbose_name='Cotización Asociada')),
            ],
            options={
                'verbose_name': 'Voucher de Pago',
                'verbose_name_plural': 'Vouchers de Pago',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_facturacion', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Ensayo')),
                ('precio_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('unidad_base', models.CharField(default='Ensayo', max_length=50)),
                ('esta_acreditado', models.BooleanField(default=False)),
                ('metodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.metodo')),
                ('norma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.norma')),
            ],
            options={
                'verbose_name': '3. Servicio / Ensayo',
                'verbose_name_plural': '3. Servicios / Ensayos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=255, verbose_name='Nombre de la Categoría/Subgrupo')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden de visualización')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='servicios.cotizacion')),
            ],
            options={
                'verbose_name': 'Grupo de Cotización',
                'verbose_name_plural': 'Grupos de Cotización',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norma_manual', models.CharField(blank=True, max_length=255, null=True, verbose_name='Norma (Manual)')),
                ('metodo_manual', models.CharField(blank=True, max_length=255, null=True, verbose_name='Método (Manual)')),
                ('descripcion_especifica', models.TextField(verbose_name='Descripción detallada para el ítem')),
                ('unidad_medida', models.CharField(default='Ensayo', max_length=50)),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_detalle', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_items', to='servicios.cotizaciongrupo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servicios.servicio', verbose_name='Servicio (Ensayo)')),
            ],
            options={
                'verbose_name': 'Detalle de Cotización',
                'ordering': ['id'],
            },
        ),
    ]
