# Generated by Django 4.2.25 on 2025-10-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='plazo_entrega_dias',
            field=models.IntegerField(default=30, verbose_name='Plazo de Entrega (Días)'),
        ),
    ]
