# Generated by Django 4.2.25 on 2025-11-06 02:32

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría (Ej: ENSAYOS EN SUELOS)')),
                ('codigo_prefijo', models.CharField(max_length=10, unique=True, verbose_name='Prefijo de Código (Ej: ES, EC, EA)')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría de Servicio',
                'verbose_name_plural': 'Categorías de Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='es_sujeto_a_presupuesto',
            field=models.BooleanField(default=False, verbose_name='¿Sujeto a Presupuesto (SP)?'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio_urgente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Unitario Urgente'),
        ),
        migrations.AlterField(
            model_name='detalleservicio',
            name='servicio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_web', to='servicios.servicio', verbose_name='Servicio Web'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio Unitario Base (Normal)'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='servicios.categoriaservicio', verbose_name='Categoría del Ensayo'),
        ),
    ]
