# Generated by Django 4.2.27 on 2026-02-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='es_plantilla',
            field=models.BooleanField(default=False, verbose_name='¿Es una Plantilla?'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='nombre_plantilla',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre identificador de la Plantilla'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='asunto_servicio',
            field=models.CharField(max_length=255, verbose_name='Asunto del Servicio'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('Plantilla', 'Plantilla (Modelo)'), ('Pendiente', 'Pendiente de Revisión'), ('Enviada', 'Enviada al Cliente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Anulada', 'Anulada')], default='Pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='numero_oferta',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de Oferta'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='persona_contacto',
            field=models.CharField(max_length=200, verbose_name='Persona de Contacto'),
        ),
    ]
