# Generated by Django 4.2.29 on 2026-04-16 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaservicio',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría Principal', 'verbose_name_plural': 'Categorías Principales'},
        ),
        migrations.AlterModelOptions(
            name='subcategoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Subcategoría', 'verbose_name_plural': 'Subcategorías'},
        ),
    ]
