# Generated by Django 4.2.25 on 2025-10-20 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_cotizacion_plazo_entrega_dias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['nombre', 'codigo_facturacion'], 'verbose_name': 'Servicio de Laboratorio', 'verbose_name_plural': 'Servicios de Laboratorio'},
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='orden',
        ),
    ]
