# Generated by Django 4.2.25 on 2025-11-07 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_categoriaservicio_servicio_es_sujeto_a_presupuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_generacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Generación de la Oferta'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='numero_oferta',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de Oferta (VCF-OTE-YYYY-XXX)'),
        ),
    ]
