# Generated by Django 4.2.29 on 2026-04-19 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("servicios", "0002_alter_categoriaservicio_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogoCondicionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_nodo",
                    models.CharField(
                        choices=[("grupo", "Grupo / Padre"), ("item", "Ítem / Viñeta")],
                        default="item",
                        max_length=20,
                        verbose_name="Tipo de nodo",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Título corto",
                    ),
                ),
                ("texto", models.TextField(verbose_name="Texto base")),
                ("orden", models.PositiveIntegerField(default=1, verbose_name="Orden")),
                (
                    "nivel",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Nivel jerárquico"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "seleccionado_por_defecto",
                    models.BooleanField(
                        default=True, verbose_name="Seleccionado por defecto"
                    ),
                ),
                (
                    "editable_en_cotizacion",
                    models.BooleanField(
                        default=True, verbose_name="¿Editable en cotización?"
                    ),
                ),
                (
                    "es_obligatorio",
                    models.BooleanField(
                        default=False, verbose_name="¿Siempre debe incluirse?"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="servicios.catalogocondicionitem",
                        verbose_name="Padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catálogo - Ítem de Condición",
                "verbose_name_plural": "Catálogo - Ítems de Condiciones",
                "ordering": ["seccion__orden", "orden", "id"],
            },
        ),
        migrations.CreateModel(
            name="CatalogoCondicionSeccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código interno"
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=255, verbose_name="Título de la sección"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("notas", "Notas"), ("lista", "Lista")],
                        default="lista",
                        max_length=20,
                        verbose_name="Tipo de presentación",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=1, verbose_name="Orden")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "es_obligatoria",
                    models.BooleanField(
                        default=False,
                        verbose_name="¿La sección siempre debe mostrarse?",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catálogo - Sección de Condición",
                "verbose_name_plural": "Catálogo - Secciones de Condiciones",
                "ordering": ["orden", "id"],
            },
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="contenido_condiciones_bloqueado",
            field=models.BooleanField(
                default=False, verbose_name="¿Contenido bloqueado para edición?"
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="contenido_condiciones_configurado",
            field=models.BooleanField(
                default=False, verbose_name="¿Se configuró el contenido dinámico?"
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="contenido_condiciones_fecha_bloqueo",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de bloqueo del contenido"
            ),
        ),
        migrations.CreateModel(
            name="CotizacionCondicionSeccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, verbose_name="Código congelado"),
                ),
                (
                    "titulo",
                    models.CharField(max_length=255, verbose_name="Título congelado"),
                ),
                (
                    "tipo",
                    models.CharField(
                        default="lista", max_length=20, verbose_name="Tipo congelado"
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=1, verbose_name="Orden")),
                (
                    "seleccionada",
                    models.BooleanField(default=True, verbose_name="Seleccionada"),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "catalogo_seccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="servicios.catalogocondicionseccion",
                        verbose_name="Sección de catálogo origen",
                    ),
                ),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condiciones_secciones",
                        to="servicios.cotizacion",
                        verbose_name="Cotización",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotización - Sección de Condición",
                "verbose_name_plural": "Cotización - Secciones de Condiciones",
                "ordering": ["orden", "id"],
            },
        ),
        migrations.CreateModel(
            name="CotizacionCondicionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_nodo",
                    models.CharField(
                        default="item", max_length=20, verbose_name="Tipo de nodo"
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Título congelado",
                    ),
                ),
                (
                    "texto_base",
                    models.TextField(verbose_name="Texto base copiado del catálogo"),
                ),
                (
                    "texto_final",
                    models.TextField(verbose_name="Texto final de la cotización"),
                ),
                ("orden", models.PositiveIntegerField(default=1, verbose_name="Orden")),
                (
                    "nivel",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Nivel jerárquico"
                    ),
                ),
                (
                    "seleccionado",
                    models.BooleanField(default=True, verbose_name="Seleccionado"),
                ),
                (
                    "es_obligatorio",
                    models.BooleanField(default=False, verbose_name="Obligatorio"),
                ),
                (
                    "editable_en_cotizacion",
                    models.BooleanField(
                        default=True, verbose_name="Editable en cotización"
                    ),
                ),
                (
                    "fue_editado",
                    models.BooleanField(
                        default=False, verbose_name="¿Fue editado respecto al base?"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "catalogo_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="servicios.catalogocondicionitem",
                        verbose_name="Ítem de catálogo origen",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="servicios.cotizacioncondicionitem",
                        verbose_name="Padre",
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="servicios.cotizacioncondicionseccion",
                        verbose_name="Sección de cotización",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotización - Ítem de Condición",
                "verbose_name_plural": "Cotización - Ítems de Condiciones",
                "ordering": ["seccion__orden", "orden", "id"],
            },
        ),
        migrations.AddField(
            model_name="catalogocondicionitem",
            name="seccion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="servicios.catalogocondicionseccion",
                verbose_name="Sección",
            ),
        ),
        migrations.AddIndex(
            model_name="cotizacioncondicionseccion",
            index=models.Index(
                fields=["cotizacion", "orden"], name="servicios_c_cotizac_a1591e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cotizacioncondicionseccion",
            index=models.Index(
                fields=["cotizacion", "codigo"], name="servicios_c_cotizac_215e15_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cotizacioncondicionseccion",
            unique_together={("cotizacion", "codigo")},
        ),
        migrations.AddIndex(
            model_name="cotizacioncondicionitem",
            index=models.Index(
                fields=["seccion", "orden"], name="servicios_c_seccion_52191d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cotizacioncondicionitem",
            index=models.Index(
                fields=["parent", "orden"], name="servicios_c_parent__ce8dfb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cotizacioncondicionitem",
            index=models.Index(
                fields=["seleccionado"], name="servicios_c_selecci_d59444_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="catalogocondicionitem",
            index=models.Index(
                fields=["seccion", "orden"], name="servicios_c_seccion_dd944f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="catalogocondicionitem",
            index=models.Index(
                fields=["parent", "orden"], name="servicios_c_parent__303381_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="catalogocondicionitem",
            index=models.Index(fields=["activo"], name="servicios_c_activo_e20fd4_idx"),
        ),
    ]
