# Generated by Django 4.2.27 on 2026-02-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_cotizacion_es_plantilla_cotizacion_nombre_plantilla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente de Revisión'), ('Enviada', 'Enviada al Cliente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Anulada', 'Anulada')], default='Pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
