# Generated by Django 4.2.25 on 2025-10-21 02:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_servicio_options_remove_servicio_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='total_detalle',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Subtotal de Línea'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='tasa_igv',
            field=models.DecimalField(decimal_places=3, default=0.18, max_digits=5, verbose_name='Tasa IGV Aplicada (Ej: 0.18)'),
        ),
    ]
