# Generated by Django 4.2.27 on 2026-03-04 14:58

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_cotizacion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plantilla', models.CharField(max_length=200, verbose_name='Nombre de la Plantilla')),
                ('asunto_referencial', models.CharField(max_length=255, verbose_name='Asunto Sugerido')),
                ('plazo_entrega_defecto', models.IntegerField(default=30)),
                ('forma_pago_defecto', models.CharField(default='Contado', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('servicio_general', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.categoriaservicio', verbose_name='Categoría General')),
            ],
            options={
                'verbose_name': 'Plantilla de Cotización',
                'verbose_name_plural': 'Plantillas de Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='PlantillaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=255, verbose_name='Nombre de la Categoría/Subgrupo')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='servicios.plantillacotizacion')),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norma_manual', models.CharField(blank=True, max_length=255, null=True)),
                ('metodo_manual', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion_especifica', models.TextField()),
                ('unidad_medida', models.CharField(default='Ensayo', max_length=50)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_detalle', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_items', to='servicios.plantillagrupo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servicios.servicio')),
            ],
        ),
    ]
