# Generated by Django 4.2.25 on 2025-11-21 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_cotizacion_fecha_generacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='servicio_general',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_por_categoria', to='servicios.categoriaservicio', verbose_name='Categoría General del Servicio (Filtro)'),
        ),
    ]
