# Generated by Django 4.2.29 on 2026-04-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_catalogocondicionitem_catalogocondicionseccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogocondicionitem',
            name='seleccionado_por_defecto',
            field=models.BooleanField(default=False, verbose_name='Seleccionado por defecto'),
        ),
        migrations.AlterField(
            model_name='cotizacioncondicionitem',
            name='seleccionado',
            field=models.BooleanField(default=False, verbose_name='Seleccionado'),
        ),
        migrations.AlterField(
            model_name='cotizacioncondicionitem',
            name='tipo_nodo',
            field=models.CharField(choices=[('grupo', 'Grupo / Padre'), ('item', 'Ítem / Viñeta')], default='item', max_length=20, verbose_name='Tipo de nodo'),
        ),
        migrations.AlterField(
            model_name='cotizacioncondicionseccion',
            name='seleccionada',
            field=models.BooleanField(default=False, verbose_name='Seleccionada'),
        ),
    ]
