# Generated by Django 4.2.27 on 2026-03-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_plantillacotizacion_plantillagrupo_plantilladetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillacotizacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
