# Generated by Django 4.2.25 on 2025-11-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_cotizacion_servicio_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente de Revisión'), ('Enviada', 'Enviada al Cliente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Anulada', 'Anulada')], default='Pendiente', max_length=20, verbose_name='Estado de la Oferta'),
        ),
    ]
