# Generated by Django 4.2.29 on 2026-04-21 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_alter_catalogocondicionitem_seleccionado_por_defecto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaCondicionSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código congelado')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título congelado')),
                ('tipo', models.CharField(default='lista', max_length=20, verbose_name='Tipo congelado')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('seleccionada', models.BooleanField(default=False, verbose_name='Seleccionada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('catalogo_seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_plantilla', to='servicios.catalogocondicionseccion', verbose_name='Sección de catálogo origen')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones_secciones', to='servicios.plantillacotizacion', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Plantilla - Sección de Condición',
                'verbose_name_plural': 'Plantilla - Secciones de Condiciones',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaCondicionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_nodo', models.CharField(choices=[('grupo', 'Grupo / Padre'), ('item', 'Ítem / Viñeta')], default='item', max_length=20, verbose_name='Tipo de nodo')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título congelado')),
                ('texto_base', models.TextField(verbose_name='Texto base copiado del catálogo')),
                ('texto_final', models.TextField(verbose_name='Texto final de la plantilla')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('nivel', models.PositiveSmallIntegerField(default=0, verbose_name='Nivel jerárquico')),
                ('seleccionado', models.BooleanField(default=False, verbose_name='Seleccionado')),
                ('es_obligatorio', models.BooleanField(default=False, verbose_name='Obligatorio')),
                ('editable_en_cotizacion', models.BooleanField(default=True, verbose_name='Editable')),
                ('fue_editado', models.BooleanField(default=False, verbose_name='¿Fue editado respecto al base?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('catalogo_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_plantilla', to='servicios.catalogocondicionitem', verbose_name='Ítem de catálogo origen')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='servicios.plantillacondicionitem', verbose_name='Padre')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='servicios.plantillacondicionseccion', verbose_name='Sección de plantilla')),
            ],
            options={
                'verbose_name': 'Plantilla - Ítem de Condición',
                'verbose_name_plural': 'Plantilla - Ítems de Condiciones',
                'ordering': ['seccion__orden', 'orden', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='plantillacondicionseccion',
            index=models.Index(fields=['plantilla', 'orden'], name='servicios_p_plantil_d51bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='plantillacondicionseccion',
            index=models.Index(fields=['plantilla', 'codigo'], name='servicios_p_plantil_c58e1b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plantillacondicionseccion',
            unique_together={('plantilla', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='plantillacondicionitem',
            index=models.Index(fields=['seccion', 'orden'], name='servicios_p_seccion_53c215_idx'),
        ),
        migrations.AddIndex(
            model_name='plantillacondicionitem',
            index=models.Index(fields=['parent', 'orden'], name='servicios_p_parent__268d8e_idx'),
        ),
        migrations.AddIndex(
            model_name='plantillacondicionitem',
            index=models.Index(fields=['seleccionado'], name='servicios_p_selecci_3c234f_idx'),
        ),
    ]
