# Generated by Django 4.2.29 on 2026-08-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_plantillacondicionseccion_plantillacondicionitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=300, verbose_name='Nombre del Ensayo'),
        ),
    ]
