# Generated by Django 4.2.25 on 2025-11-23 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_alter_cotizacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='documento_firmado',
            field=models.FileField(blank=True, null=True, upload_to='vouchers/documentos_firmados/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Oferta/Contrato Firmado por Cliente'),
        ),
    ]
