# Generated by Django 4.2.29 on 2026-08-23 15:56

from django.db import migrations, models
import django.db.models.deletion
import grupovicaf.seo


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nosotros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Si se deja en blanco, se usa el título natural de la página.",
                        max_length=60,
                        validators=[grupovicaf.seo.validar_meta_title],
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        validators=[grupovicaf.seo.validar_meta_description],
                    ),
                ),
                ("noindex", models.BooleanField(default=False)),
                ("imagen_og", models.ImageField(blank=True, upload_to="seo/og/")),
                ("titulo", models.CharField(max_length=100)),
                ("contenido", models.TextField()),
                ("imagen", models.ImageField(blank=True, upload_to="nosotros/")),
                (
                    "imagen_alt",
                    models.CharField(
                        blank=True,
                        help_text="Obligatorio si se sube imagen: describe la escena para accesibilidad y SEO.",
                        max_length=125,
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Nosotros",
                "verbose_name_plural": "Nosotros",
            },
        ),
        migrations.CreateModel(
            name="TipoDocumentoNosotros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Si se deja en blanco, se usa el título natural de la página.",
                        max_length=60,
                        validators=[grupovicaf.seo.validar_meta_title],
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        validators=[grupovicaf.seo.validar_meta_description],
                    ),
                ),
                ("noindex", models.BooleanField(default=False)),
                ("imagen_og", models.ImageField(blank=True, upload_to="seo/og/")),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipo de documento",
                "verbose_name_plural": "Tipos de documento",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoNosotros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen de portada o miniatura del documento.",
                        upload_to="nosotros/documentos/imagenes/",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        help_text="Subir PDF, imagen, Word, Excel o PowerPoint.",
                        upload_to="nosotros/documentos/archivos/",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                (
                    "destacado",
                    models.BooleanField(
                        default=False,
                        help_text="Marcar si deseas priorizar este documento entre los primeros visibles.",
                    ),
                ),
                ("fecha_publicacion", models.DateField(blank=True, null=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos",
                        to="web_nosotros.tipodocumentonosotros",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Nosotros",
                "verbose_name_plural": "Documentos de Nosotros",
                "ordering": ["orden", "-destacado", "-creado"],
            },
        ),
    ]
