# Generated by Django 4.2.29 on 2026-08-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_nosotros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosotros',
            name='mision',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nosotros',
            name='vision',
            field=models.TextField(blank=True),
        ),
    ]
