# Generated by Django 4.2.29 on 2026-08-23 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("servicios", "0006_alter_servicio_nombre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Acreditacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organismo", models.CharField(default="INACAL", max_length=150)),
                (
                    "numero_acreditacion",
                    models.CharField(max_length=50, verbose_name="N.º de acreditación"),
                ),
                (
                    "alcance",
                    models.TextField(
                        help_text="Descripción del alcance de acreditación (qué ensayos cubre)."
                    ),
                ),
                ("vigencia_desde", models.DateField(blank=True, null=True)),
                ("vigencia_hasta", models.DateField(blank=True, null=True)),
                (
                    "documento",
                    models.FileField(
                        blank=True,
                        help_text="Certificado de acreditación en PDF.",
                        upload_to="acreditacion/documentos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, upload_to="acreditacion/logos/"),
                ),
                (
                    "logo_alt",
                    models.CharField(
                        blank=True,
                        help_text="Obligatorio si se sube logo: describe el logo para accesibilidad y SEO.",
                        max_length=125,
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "servicios_acreditados",
                    models.ManyToManyField(
                        blank=True,
                        related_name="acreditaciones",
                        to="servicios.servicio",
                        verbose_name="Ensayos acreditados",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acreditación",
                "verbose_name_plural": "Acreditaciones",
                "ordering": ["orden", "-vigencia_desde"],
            },
        ),
    ]
