# Generated by Django 4.2.27 on 2026-01-31 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RolTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Rol')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de Responsabilidades')),
            ],
            options={
                'verbose_name': 'Rol del Trabajador',
                'verbose_name_plural': 'Roles del Trabajador',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TrabajadorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('titulo_profesional', models.CharField(blank=True, max_length=50, null=True, verbose_name='Título Profesional (Ej: Ing., Bach.)')),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto')),
                ('correo_contacto', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo de Contacto')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='trabajadores_fotos/', verbose_name='Foto de Perfil')),
                ('firma_electronica', models.ImageField(blank=True, null=True, upload_to='firmas/', verbose_name='Firma Electrónica para Informes')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='URL de LinkedIn')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfiles', to='trabajadores.roltrabajador', verbose_name='Rol en el Sistema')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Sistema')),
            ],
            options={
                'verbose_name': 'Perfil de Trabajador',
                'verbose_name_plural': 'Perfiles de Trabajadores',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
