# Generated by Django 4.2.25 on 2026-01-17 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Rol')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de Responsabilidades')),
            ],
            options={
                'verbose_name': 'Rol del Trabajador',
                'verbose_name_plural': 'Roles del Trabajador',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='trabajadorprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='trabajadorprofile',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='perfiles', to='trabajadores.roltrabajador', verbose_name='Rol en el Sistema'),
            preserve_default=False,
        ),
    ]
