# Generated by Django 4.2.29 on 2026-05-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Permiso')),
                ('modulo', models.CharField(max_length=100, verbose_name='Módulo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Permiso de Módulo',
                'verbose_name_plural': 'Permisos de Módulo',
                'ordering': ['modulo', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='roltrabajador',
            name='permisos',
            field=models.ManyToManyField(blank=True, related_name='roles', to='trabajadores.permisomodulo', verbose_name='Permisos del Rol'),
        ),
    ]
