# Generated by Django 4.2.29 on 2026-05-09 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0003_permisomodulo_activo_permisomodulo_actualizado_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Acción')),
                ('codigo', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Acción de Permiso',
                'verbose_name_plural': 'Acciones de Permisos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ModuloSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Módulo')),
                ('codigo', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('icono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icono Lucide')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Módulo del Sistema',
                'verbose_name_plural': 'Módulos del Sistema',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='permisomodulo',
            name='codigo',
            field=models.CharField(max_length=150, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='permisomodulo',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre del Permiso'),
        ),
        migrations.AddField(
            model_name='permisomodulo',
            name='accion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permisos', to='trabajadores.accionpermiso', verbose_name='Acción'),
        ),
        migrations.AddField(
            model_name='permisomodulo',
            name='modulo_sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permisos', to='trabajadores.modulosistema', verbose_name='Módulo del Sistema'),
        ),
    ]
