# Generated by Django 4.2.29 on 2026-05-09 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0005_poblar_modulos_acciones_permisos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisomodulo',
            options={'ordering': ['modulo_sistema__orden', 'modulo_sistema__nombre', 'accion__orden', 'accion__nombre'], 'verbose_name': 'Permiso de Módulo', 'verbose_name_plural': 'Permisos de Módulo'},
        ),
        migrations.AlterField(
            model_name='permisomodulo',
            name='accion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permisos', to='trabajadores.accionpermiso', verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='permisomodulo',
            name='codigo',
            field=models.CharField(editable=False, max_length=150, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='permisomodulo',
            name='modulo_sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permisos', to='trabajadores.modulosistema', verbose_name='Módulo del Sistema'),
        ),
        migrations.AlterField(
            model_name='permisomodulo',
            name='nombre',
            field=models.CharField(editable=False, max_length=150, verbose_name='Nombre del Permiso'),
        ),
        migrations.AlterUniqueTogether(
            name='permisomodulo',
            unique_together={('modulo_sistema', 'accion')},
        ),
        migrations.RemoveField(
            model_name='permisomodulo',
            name='modulo',
        ),
    ]
