# Generated by Django 4.2.25 on 2026-01-13 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(help_text='Número de RUC de 11 dígitos. Debe ser único.', max_length=11, unique=True, verbose_name='RUC (N° de Identificación Tributaria)')),
                ('razon_social', models.CharField(help_text='Nombre legal o comercial de la empresa cliente.', max_length=255, unique=True, verbose_name='Razón Social / Nombre de la Empresa')),
                ('direccion', models.CharField(blank=True, help_text='Dirección principal de la empresa.', max_length=255, null=True, verbose_name='Dirección Fiscal')),
                ('sitio_web', models.URLField(blank=True, max_length=255, null=True, verbose_name='Página Web')),
                ('persona_contacto', models.CharField(max_length=255, verbose_name='Persona de Contacto Principal')),
                ('cargo_contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo del Contacto')),
                ('celular_contacto', models.CharField(max_length=20, verbose_name='Celular del Contacto')),
                ('correo_contacto', models.EmailField(max_length=255, verbose_name='Correo Electrónico del Contacto')),
                ('firma_electronica', models.ImageField(blank=True, null=True, upload_to='firmas_clientes/', verbose_name='Firma Electrónica')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el cliente está habilitado.', verbose_name='Cliente Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['razon_social'],
            },
        ),
    ]
