# Generated by Django 4.2.27 on 2026-01-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='logo_empresa',
            field=models.ImageField(blank=True, help_text='Imagen opcional para personalizar informes.', null=True, upload_to='clientes/logos/%Y/%m/', verbose_name='Logo de la Empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Cliente Activo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección Fiscal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='firma_electronica',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/firmas/%Y/%m/', verbose_name='Firma Electrónica'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['codigo_confidencial'], name='clientes_cl_codigo__f3117c_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['ruc'], name='clientes_cl_ruc_79b45b_idx'),
        ),
    ]
