# Generated by Django 4.2.29 on 2026-08-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="origen",
            field=models.CharField(
                choices=[
                    ("lims", "Registrado en el LIMS"),
                    ("web", "Solicitud desde la web pública"),
                ],
                default="lims",
                help_text="'web' marca los clientes creados automáticamente desde una solicitud de cotización pública.",
                max_length=10,
                verbose_name="Origen del registro",
            ),
        ),
    ]
