# Generated by Django 4.2.29 on 2026-08-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siteconfig', '0001_set_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegocioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Grupo VICAF SAC', max_length=150)),
                ('descripcion', models.CharField(max_length=300)),
                ('direccion_calle', models.CharField(max_length=200)),
                ('direccion_localidad', models.CharField(default='Cajamarca', max_length=100)),
                ('direccion_region', models.CharField(default='Cajamarca', max_length=100)),
                ('direccion_codigo_postal', models.CharField(blank=True, max_length=20)),
                ('direccion_pais', models.CharField(default='PE', max_length=2)),
                ('telefono', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(default='informes@grupovicaf.com', max_length=254)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('horario_semana_apertura', models.TimeField(blank=True, null=True)),
                ('horario_semana_cierre', models.TimeField(blank=True, null=True)),
                ('horario_sabado_apertura', models.TimeField(blank=True, null=True)),
                ('horario_sabado_cierre', models.TimeField(blank=True, null=True)),
                ('ciudades_cobertura', models.JSONField(blank=True, default=list)),
                ('acreditacion_entidad', models.CharField(default='INACAL', max_length=100)),
                ('acreditacion_codigo', models.CharField(default='LE-230', max_length=50)),
                ('linkedin_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Configuración del negocio',
                'verbose_name_plural': 'Configuración del negocio',
            },
        ),
    ]
