# Generated by Django 4.2.29 on 2026-08-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0003_seed_negocioconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocioconfig',
            name='ruc',
            field=models.CharField(blank=True, help_text='RUC de la propia empresa (dato público, no confundir con clientes.Cliente.ruc). Se muestra en la barra inferior del footer.', max_length=11),
        ),
    ]
